apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: khauarey4-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/khauarey4-java-springboot-gitops